[package]
name = "mbn_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "mbn_python"
crate-type = ["cdylib"]

[dependencies]
mbn = {path = "../mbn" , features =["python"]}
pyo3 = { workspace = true }


[build-dependencies]
pyo3-build-config = { workspace = true }
