[package]
name = "mbe_python"
version = "1.0.0"
edition = "2021"

[lib]
name = "mbe_python"
crate-type = ["cdylib"]

[dependencies]
mbe = {path = "../rust" , features =["python"]}
pyo3 = { workspace = true }


[build-dependencies]
pyo3-build-config = { workspace = true }
